/**
 * Copyright (2018, ) Institute of Software, Chinese Academy of Sciences
 */
package com.github.kubesys.webfrk;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.InterceptorRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

import com.github.kubesys.webfrk.core.CorsInterceptor;



/**
 * @author wuheng(@iscas.ac.cn)
 * @since 2019/2/20
 * 
 *        <p>
 *        The {@code ApplicationServer} class is generated by Spring cloud
 *        framework. You can invoke the main method to start this program for
 *        debugging in development, or running in production
 * 
 *        <p>
 *        Note: do not modify this class
 */
@Configuration
@SpringBootApplication
@EnableAutoConfiguration
@ComponentScan(basePackages= {"com.github.kubesys.webfrk", "com.github.uitplus"})
public class ApplicationServer implements WebMvcConfigurer {

	/**
	 * program entry point
	 * 
	 * @param args default is null
	 */
	public static void main(String[] args) {
		SpringApplication.run(ApplicationServer.class, args);
	}

	@Override
	public void addInterceptors(InterceptorRegistry registry) {
		registry.addInterceptor(new CorsInterceptor())
						.addPathPatterns("/**");
	}

}
